### ISSUE TITLE
Change all methods to retrieve the permissions from the user object (not from the user group)

### ISSUE THREAD

**Issue by helllth** [cismet/cids-server#16]
this will give us the option to handle a user without a usergroup in the userobject. (e.g. use all groups to aggregate all permissions)

**Comment by p-a-s-c-a-l** [comment]
NPE in [PermissionHolder.java#L94](https://github.com/cismet/cids-server/blob/b6c113515364ec4c7c4e4fd65b6d30a5c3fa830a/src/main/java/Sirius/server/newuser/permission/PermissionHolder.java#L94) if UserGroup of a User is null!
-> If UserGroup is null, permissions of all potential user groups shall be collected!

- Add potential user groups check in [ObjectFactory.java#L1143](https://github.com/cismet/cids-server/blob/feature/188-integrate-action-api-enhancements/src/main/java/Sirius/server/localserver/object/ObjectFactory.java#L1143) (see [VirtualTree.java#L1061](https://github.com/cismet/cids-server/blob/feature/188-integrate-action-api-enhancements/src/main/java/Sirius/server/localserver/tree/VirtualTree.java#L1061)) or remove  public void addPermission(final UserGroup ug, final Permission perm)
- Revert changes in https://github.com/cismet/cids-server-rest-legacy/issues/34
